<<<<<<< HEAD
// Generated by https://quicktype.io

=======

// Generated by https://quicktype.io
>>>>>>> fin-seccion-9
export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
